version: "3.7"  #
services:  
  reactfrontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend 
    ports:
      - "888:80"    #external:internal frontend 
    depends_on:
      - db
  nodebackend:
    build: 
      context: ../server
      dockerfile: Dockerfile.backend  
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db   
              
  db:
    volumes:
      - /Users/ellarnol/localTwitterDB:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"             
